-- Migration: Add thumbnail_url column to photos table
-- This is needed for the Railway backend's image processing

-- Add thumbnail_url column to store optimized thumbnail images
ALTER TABLE public.photos 
ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_photos_thumbnail_url ON public.photos(thumbnail_url);

-- Comments
COMMENT ON COLUMN public.photos.thumbnail_url IS 'URL to the compressed thumbnail version of the photo (generated by backend)';
